# Generated by Django 4.2.7 on 2023-12-11 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=400)),
                ('caracteristicas', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.FileField(upload_to='productos/')),
                ('ref_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
                ('ref_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.estadoproducto')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='ref_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipoproducto'),
        ),
    ]
