# Generated by Django 4.2.7 on 2023-12-11 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='ref_animal',
            new_name='ref_tipoproducto',
        ),
    ]
